### ISSUE TITLE
[Bug Report] Image Uploaded from WYSIWYG Editor Saved as Base64 to Firestore

### ISSUE THREAD

**Issue by jefrydco** [oddbit/tanam#13]
Hi, recently I found your cms from my friend, and I think this is another great firebase cms. But when I observer how the wysiwyg worked, I found that the image uploaded from there saved as base64 to firestore, not saved in cloud storage.

**Comment by DennisAlund** [comment]
Thanks for the feedback. It's an issue that we've been trying to ignore at an early stage. We also ran into it, looked at it a bit and decided to work around it until we had fixed some other issues. 

There is a workaround for it until we've fixed it:
 1. Manually upload a photo to the gallery
 2. Reference the URL to the newly uploaded photo in WYSIWYG

**Comment by DennisAlund** [comment]
The whole admin interface is being rewritten in Angular. This issue will be resolved when that is completed. Please follow progress in the [`angular`](https://github.com/oddbit/tanam/tree/angular) branch.
