### ISSUE TITLE
Add some detail on system notification

### ISSUE THREAD

**Issue by detautama** [oddbit/tanam#137]
Some detail of an notification need to be added like date and message (can truncate the character)

Can use references from book firebase notification
![error notification](https://user-images.githubusercontent.com/18025983/57117349-f2a18a00-6d8d-11e9-8e78-12973da9521c.png)

**Comment by DennisAlund** [comment]
Make sure to merge #141 before this one. There are some updates to the `SystemNotification` type.

**Comment by detautama** [comment]
> Make sure to merge #141 before this one. There are some updates to the `SystemNotification` type.

#141 Merged
