### ISSUE TITLE
Put URL column in the document table

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#163]
Add a column for document URL in the overview list, similar to #160

**Comment by detautama** [comment]
> Add a column for document URL in the overview list, similar to #160

What is the function of URL ? is that same as slug ?

**Comment by DennisAlund** [comment]
Yes, but without the domain part. Just the data from the document `url` field, such as: `/blog/test-blog-post`

![image](https://user-images.githubusercontent.com/2051607/57782612-2baf0680-775f-11e9-863b-03380337804a.png)

**Comment by DennisAlund** [comment]
Duplicate of #160
