### ISSUE TITLE
What is the status of the project? 

### ISSUE THREAD

**Issue by dimaportenko** [oddbit/tanam#286]
I see that the last contribution was 2 years ago, what is the status of this project?

**Comment by anukools** [comment]
This project looks good but haven't been updated. Any alternation to this with Firebase for CMS ?

**Comment by dimaportenko** [comment]
I guess you can find something here https://firebaseopensource.com/

**Comment by DennisAlund** [comment]
Sorry for leaving you unattended. It is not up to my standards of community support. The project was asleep and I guess I was overwhelmed with other things. We're working on a little rewrite right now.
