### ISSUE TITLE
Make images fit inside the cards in media gallery

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#30]
![image](https://user-images.githubusercontent.com/2051607/51373011-f17b8280-1b39-11e9-8ef8-b3c390b692d2.png)

The styling of media gallery is broken and images doesn't scale down to **fit the width** of their card.

Expected behavior is that the image is proportionally scaled down to fit inside the card (center crop or something like that to zoom to best fit that fills the width of the card.

**Comment by detautama** [comment]
Finished by this commit: https://github.com/oddbit/tanam/commit/1b28259c203bd4bfd0e808ba4b690d4a6dcf3a6e
