### ISSUE TITLE
Implement Settings Page

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#350]
## Description
We need to implement a settings page for the application. This page will allow users to configure site settings. The implementation should include the following features:

### Requirements

1. **Navigation to Settings Page**:
   - When a user clicks on the settings menu item in the sidebar, it should navigate to the URL `/settings`.

2. **Settings Page**:
   - The settings page should contain form elements for configuring site settings specific to each site, using the URL pattern `/tanam/{site}`.

3. **Form Elements**:
   - Reference for form elements: [TailAdmin Form Elements](https://nextjs-demo.tailadmin.com/forms/form-elements).
   - Include form fields for various site settings, such as site title, description, logo upload, contact information, and any other relevant configurations.

**Comment by WidaSuryani** [comment]
Hi @DennisAlund Sorry I've question with this point :

`Settings Page:`
> The settings page should contain form elements for configuring site settings specific to each site, using the URL pattern /tanam/{site}.

Currently, we are not having `/tanam/{site}`, but on the branch `next`  we are using  `http://localhost:3000/dashboard` same like on this image
<img width="1675" alt="image" src="https://github.com/oddbit/tanam/assets/51318991/338d11b1-7c10-4ee7-ac05-e7afdcc08137">

could you please tell me more about that? 🙂

Thank you!🙏🏻

**Comment by DennisAlund** [comment]
I think I'll close this issue for now. Since we changed into a single instance per project, the settings becomes a bit questionable. Probably makes more sense to configure things over remote config instead.

Let's close this issue and you can remove the "settings" menu option in the left side menu 🙏
