### ISSUE TITLE
[Bug] Signing out doesn't redirect out of the app

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#365]
# Description
When clicking "log out" the app is signing out the user but doesn't navigate out to the sign-in page
![Jun-04-2024 10-58-30](https://github.com/oddbit/tanam/assets/2051607/644ff740-a6a0-4cb8-b92e-c12f60ff4dc8)

# Expectation
The app should "throw the user out" if signed out. 

# Requirement
The app should do the route navigation in the auth state observable (when the auth state changes to `null` then route the user to `/`)

It **should not** be done by using a route navigation when clicking "logout" since the user can be logged out for external reasons such as invalidation of the current session (resetting password on other device etc).

**Comment by DennisAlund** [comment]
I think it is as simple as just adding a redirect in the `onAuthStateChanged` subscription

```typescript
```

**Comment by muzanella11** [comment]
> I think it is as simple as just adding a redirect in the `onAuthStateChanged` subscription
> 
> ```ts
>  useEffect(() => {
>     const unsubscribe = firebaseAuth.onAuthStateChanged((user) => {
>       console.log("[onAuthStateChanged]", {user});
>       setUser(user);
>       setIsSignedIn(!!user);
> 
>       if (!user) {
>         router.push("/");
>       }
>     });
> ```

Getting this error when using this approach
![Screen Shot 2024-06-26 at 16 33 57](https://github.com/oddbit/tanam/assets/12839006/71754159-8fb5-4df5-b08e-96ab0fe1e477)
<img width="829" alt="Screen Shot 2024-06-26 at 16 33 08" src="https://github.com/oddbit/tanam/assets/12839006/927d9ef9-c0c4-4d6d-95ed-cf09f1e42823">

Still looking for a way out of this

**Comment by DennisAlund** [comment]
How about moving the `router.push()` into its own useEffect that depends on the value of `isSignedIn`?

```typescript
useEffect(() => {
   if (isSignedIn === false) {
     router.push("/");
   }
}, [isSignedIn]);
```
