### ISSUE TITLE
Add Functionality to Change Paragraph Style for Highlighted Text

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#375]
## Description

Enhance the Tiptap editor by adding functionality to change the paragraph style of highlighted text when selecting an option from the "Paragraph" dropdown menu. 

- Paragraph
- Heading 1
- Heading 2
- Heading 3
- Bullet list
- Numbered list

### Steps to Accomplish

1. **Update Toolbar/Bubble Menu**:
   - Add the "Paragraph" dropdown to the Tiptap editor's toolbar or bubble menu.

2. **Implement Functionality**:
   - Implement functionality to change the style of highlighted text based on the selected dropdown option.
   - Use Tiptap’s existing commands and schema to apply the corresponding styles.

3. **Test Changes**:
   - Test the dropdown functionality to ensure it correctly changes the paragraph style of highlighted text.

**Comment by muzanella11** [comment]
Paragraph, Heading 1, Heading 2, Heading 3 done ✅ 

https://github.com/user-attachments/assets/e837bc3f-4efb-4456-a1ac-e44d825c1e88
