### ISSUE TITLE
Add Functionality to Change Style for Highlighted Text 

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#376]
## Description

Enhance the Tiptap editor by adding functionality to change the style of highlighted text when selecting a styling option

- Bold
- Italic
- Underline
- Strikethrough

### Steps to Accomplish

1. **Implement Functionality**:
   - Implement functionality to change the style of highlighted text based on the selected option.
   - Use Tiptap’s existing commands and schema to apply the corresponding styles.

2. **Test Changes**:
   - Test the dropdown functionality to ensure it correctly changes the paragraph style of highlighted text.

**Comment by muzanella11** [comment]
Done ✅ 
![Screen Shot 2024-07-10 at 15 14 35](https://github.com/oddbit/tanam/assets/12839006/85634854-7592-4da2-a190-245ef544fa83)
