### ISSUE TITLE
Add Code Block Formatting with Syntax Highlighting to Tiptap Editor

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#377]
## Description

Implement the ability to format selected text as a code block in the Tiptap editor. The code block should also support syntax highlighting for various programming languages.

### Requirements

1. **Code Block Formatting**:
   - When text is selected and the code block option is chosen, the selected text should be formatted as a code block.

2. **Syntax Highlighting**:
   - The code block should support syntax highlighting for different programming languages.
   - Highlight.js or a similar library should be used for syntax highlighting.

3. **Menu Integration**:
   - Add an option to format text as a code block in the editor's bubble menu or toolbar.

### Screenshots
![Jun-27-2024 16-12-17](https://github.com/oddbit/tanam/assets/2051607/529be19e-a4dc-4f44-a135-48bef4135675)

**Comment by muzanella11** [comment]
Done ✅ 
![Screen Shot 2024-07-10 at 15 54 29](https://github.com/oddbit/tanam/assets/12839006/f8ab9fc5-7e03-4082-9c60-c23318e93db1)
