### ISSUE TITLE
Add Link Formatting to Tiptap Editor

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#378]
## Description

Implement the ability to format selected text as a hyperlink in the Tiptap editor. The link should allow users to enter a URL and apply it to the selected text.

### Requirements

1. **Link Formatting**:
   - When text is selected and the link option is chosen, a dialog should appear allowing the user to enter a URL.
   - The selected text should be formatted as a hyperlink pointing to the entered URL.

2. **Menu Integration**:
   - Add an option to the editor's bubble menu or toolbar to format selected text as a link.

3. **Link Dialog**:
   - The link dialog should look and behave like the screenshot below

### Screenshot
![Jun-27-2024 16-15-46](https://github.com/oddbit/tanam/assets/2051607/45b5d997-7013-45dc-92ea-272bccb51f0a)

**Comment by muzanella11** [comment]
Done ✅ 

https://github.com/user-attachments/assets/2fdef3ad-4116-4983-91a2-5210a7a23965
