### ISSUE TITLE
Add Bullet Point and Numbered List Formatting to Tiptap Editor

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#379]
# Description

Implement the ability to format selected text as a bullet point list or a numbered list in the Tiptap editor. The user should be able to toggle between list types and apply the formatting to the selected text.

### Requirements

1. **Bullet Point List Formatting**:
   - When the bullet point list option is chosen, the selected text should be formatted as a bullet point list.

2. **Numbered List Formatting**:
   - When the numbered list option is chosen, the selected text should be formatted as a numbered list.

3. **Menu Integration**:
   - Add options to the editor's bubble menu or toolbar to format selected text as a bullet point list or numbered list.

**Comment by muzanella11** [comment]
Done ✅ 

https://github.com/user-attachments/assets/bdc74ea5-b5bd-48a0-a507-bcbbf1896ccd
