### ISSUE TITLE
User should be able to add Google Analytics tracking code to settings

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#86]
Adding a [Google Analytics](https://analytics.google.com/analytics/web/) tracking code (or a [Tag Manager](https://tagmanager.google.com/) code) should automatically inject and configure a the script snipped on all web pages.

Tanam should be able to detect which type of code that has been entered by the format of the tracking code.

For example.

 - `UA-92412576-1` - Google Analytics
 - `GTM-KS9LSVW` - Google Tag manager

**Comment by detautama** [comment]
WIP on branch https://github.com/oddbit/tanam/tree/issue/86-user-add-google-analytics-tracking-code
