### ISSUE TITLE
Templates are not keeping line breaks 

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#91]
# Observation
Templates are not keeping line breaks after being saved to Firestore

![image](https://user-images.githubusercontent.com/2051607/56116588-cd90d700-5f98-11e9-8c75-6dbdebdddaf8.png)

# Expectation
Line breaks and formatting such as tabs, and spaces should be kept "as is" when saving and reading data from Firestore.
![image](https://user-images.githubusercontent.com/2051607/56117039-d635dd00-5f99-11e9-8467-baa06d401a33.png)

# Analysis
Please see [related post on StackOverflow](https://stackoverflow.com/a/54639126/7967164) that are narrowing down the problem to probably being an issue of reading the data from Firestore and putting it into CKEditor.

**Comment by detautama** [comment]
Already works
